src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuthorRepository::class)]
class Author
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?int $nb_books = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Book::class)]
    private Collection $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getNbBooks(): ?int
    {
        return $this->nb_books;
    }

    public function setNbBooks(int $nb_books): static
    {
        $this->nb_books = $nb_books;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): static
    {
        if (!$this->books->contains($book)) {
            $this->books->add($book);
            $book->setAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): static
    {
        if ($this->books->removeElement($book)) {
            // set the owning side to null (unless already changed)
            if ($book->getAuthor() === $this) {
                $book->setAuthor(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return(String) $this->getUsername();
    }

}

src/Controller/AllAuthorController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use App\Form\AuthorType;
use App\Repository\AuthorRepository;
//use Doctrine\Persistence\ManagerRegistry;
use Doctrine\Persistence\ManagerRegistry;
use \Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request ;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class AllAuthorController extends AbstractController
{
//            $authors = array( array('id' => 1,'username' =>
//            'Victor Hugo', 'email' =>
//            'victor.hugo@gmail.com ', 'nb_books' => 100), array('id' => 2,'username' => ' William Shakespeare', 'email' =>
//            ' william.shakespeare@gmail.com', 'nb_books' => 200 ), array('id' => 3, 'username' => 'Taha Hussein', 'email' =>
//            'taha.hussein@gmail.com', 'nb_books' => 300),
//        );

    #[Route('/all/author', name: 'app_all_author')]
    public function index(Request $request ,AuthorRepository $repository): Response
    {
//        $numberMin = $request->query->get('number_min');
//        $numberMax = $request->query->get('number_max');
           $cn = $repository ->SearchAuthorDQLByFirstCaracterName();
        //        $authors = $repository ->SearchAuthorDQLByFirstCaracterName();
        return $this->render('author/index.html.twig', [
            'authors' => $cn
        ]);
    }

    #[Route('/add/author', name: 'add_author')]
    public function addBook(Request $request ,AuthorRepository $repository ,ManagerRegistry $managerRegistry ,ValidatorInterface $validator , ):Response
    {
        $author= new Author();
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $errors = $validator->validate($author);
            if (count($errors) > 0) {
                return new Response((string) $errors, 400);
            }
            $emailexist = $repository->findOneBy(['email' => $author->getEmail()]);
            if ($emailexist){
                return  new Response("email exist");
            }else{
                $em = $managerRegistry->getManager();
                $em->persist($author);
                $em->flush();
                return $this->redirectToRoute('app_all_author');
            }
        }
        return $this->render('author/add.html.twig', ['form' => $form->createView()]);
    }


    #[Route('/update/author/{id}', name: 'update_author')]
    public function update(Request $request,AuthorRepository $repository ,int $id ,  ManagerRegistry $managerRegistry): Response
    {
        $em= $managerRegistry->getManager();
        $author = $repository->find($id);
        if (!$author){
            return $this->render('author/error.html.twig');
        }
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            return $this->redirecttoRoute("app_all_author");
        }

        return $this->render('author/update.html.twig', [
            'form' => $form->createView(),
        ]);
    }


    #[Route('/delete/author/{id}', name: 'delete_author')]
    public function delete($id,AuthorRepository $repository,ManagerRegistry $managerRegistry): Response
    {
        $author = $repository ->find($id);
        if ($author->getNbBooks() == 0) {
            $em = $managerRegistry->getManager();
            $em->remove($author);
            $em->flush();
            return $this->redirecttoRoute("app_all_author");
        }else {
            return  new Response("u can't delete this author");
        }
    }

    #[Route('/author_details/{id}', name: 'author_details')]
    public function details($id , AuthorRepository $repository): Response
    {
        $author = $repository->find($id);
        return $this->render('author/details.html.twig', [
            'author' => $author,
        ]);

    }


}

templates/all_author/index.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        /* Add a border to the table */
        table {
            border: 2px black solid; /* 2px black solid border */
            border-collapse: collapse; /* Collapse the border so there are no spaces between cells */
            width: 100%; /* Set the table width to 100% of its container */
            font-family: Arial, sans-serif; /* Change the font family */
        }

        /* Style for table headers */
        th {
            border: 2px black solid;
            background-color: #86c786; /* Gray background color for headers */
            color: white; /* Text color */
            padding: 10px; /* Add padding for better spacing */
        }

        /* Style for table data cells */
        td {
            border: 2px black solid;
            padding: 8px; /* Add padding for better spacing */
            text-align: center; /* Center-align text in cells */
        }
    </style>
    <title>List of Authors</title>
</head>
<body>
{% set sum = 0 %}
{% if authors |length == 0 %}
<h5> table vide</h5>
{% else %}
<table >
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Number Book</th>
        <th>Details</th>
    </tr>
    </thead>
    <tbody>

    {% for author in authors %}
        <tr>
            <td>{{ author.id }}</td>
            <td>{{ author.username |upper}}</td>
            <td>{{ author.email }}</td>
            <td>{{ author.nbBooks }}</td>
            <td>
                <a href="{{ path('author_details', {'id': author.id}) }}">Show More</a>
            </td>
            {% set sum = sum+author.nbBooks %}
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endif %}
Length of table :{{ authors |length}} <br>
Total number of books{{ sum}}
</body>
</html>